### GET
http://localhost:5000/api/get/books

### GET
http://localhost:5000/books

### GET
http://localhost:5000/api/get/book/info/add/{{id}}

### GET
http://localhost:5000/api/get/book/info/delete/{{id}}

### GET
http://localhost:5000/api/get/book/info/edit/{{id}}

### GET
http://localhost:5000/api/get/auth/login

### GET
http://localhost:5000/api/get/admin/user-info

### GET
http://localhost:5000/api/get/blog/posts